// <auto-generated />
using System;
using CLG.OperationsAPI.Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediatorPatternAPI.Migrations
{
    [DbContext(typeof(OperationContext))]
    [Migration("20230205171927_initial_migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CLG.OperationsAPI.Application.Entity.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DateOp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DateOp");

                    b.Property<string>("DescriptionOp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DescriptionOp");

                    b.Property<int>("TypeOp")
                        .HasColumnType("int")
                        .HasColumnName("TypeOp");

                    b.Property<double>("ValueOp")
                        .HasColumnType("double")
                        .HasColumnName("ValueOp");

                    b.HasKey("Id");

                    b.ToTable("operations");
                });
#pragma warning restore 612, 618
        }
    }
}
